import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "DejoTools terms of service - understand the rules and guidelines for using our free online tools.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">Terms of Service</h1>
      
      <div className="prose dark:prose-invert max-w-none">
        <p className="text-gray-600 dark:text-gray-400 mb-6">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-600 dark:text-gray-400">
            By accessing and using DejoTools ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">2. Description of Service</h2>
          <p className="text-gray-600 dark:text-gray-400">
            DejoTools provides free online tools including image converters, PDF utilities, creator tools, and developer utilities. All processing is performed locally in your browser - your files are not uploaded to our servers.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">3. Use of Service</h2>
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            You agree to use the Service only for lawful purposes. You may not:
          </p>
          <ul className="list-disc list-inside text-gray-600 dark:text-gray-400 space-y-2">
            <li>Use the Service for any illegal or unauthorized purpose</li>
            <li>Process files that you do not have the right to modify or distribute</li>
            <li>Attempt to interfere with or disrupt the Service</li>
            <li>Use automated systems to access the Service excessively</li>
            <li>Violate any applicable laws or regulations</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">4. Intellectual Property</h2>
          <p className="text-gray-600 dark:text-gray-400">
            The Service and its original content, features, and functionality are owned by DejoTools and are protected by international copyright, trademark, and other intellectual property laws. You retain all rights to the files you process using our tools.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">5. Disclaimer of Warranties</h2>
          <p className="text-gray-600 dark:text-gray-400">
            The Service is provided "as is" and "as available" without any warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, secure, or error-free. We do not guarantee the accuracy, completeness, or usefulness of any output generated by our tools.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">6. Limitation of Liability</h2>
          <p className="text-gray-600 dark:text-gray-400">
            In no event shall DejoTools be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or other intangible losses, resulting from your use of the Service or any content obtained from the Service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">7. User Responsibility</h2>
          <p className="text-gray-600 dark:text-gray-400">
            You are solely responsible for:
          </p>
          <ul className="list-disc list-inside text-gray-600 dark:text-gray-400 space-y-2 mt-4">
            <li>Ensuring you have the right to process any files you upload</li>
            <li>Maintaining backups of your original files</li>
            <li>Verifying the output of any conversions or modifications</li>
            <li>Complying with all applicable laws and regulations</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">8. Modifications to Service</h2>
          <p className="text-gray-600 dark:text-gray-400">
            We reserve the right to modify, suspend, or discontinue the Service at any time without notice. We may also modify these Terms of Service at any time by posting the revised terms on our website.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">9. Advertising</h2>
          <p className="text-gray-600 dark:text-gray-400">
            The Service may include advertisements provided by third-party advertising networks. We are not responsible for the content of any third-party advertisements.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">10. Governing Law</h2>
          <p className="text-gray-600 dark:text-gray-400">
            These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">11. Contact</h2>
          <p className="text-gray-600 dark:text-gray-400">
            If you have any questions about these Terms of Service, please contact us through our website.
          </p>
        </section>
      </div>
    </div>
  );
}
